server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: allen123
    url: jdbc:mysql://localhost:3306/assignment?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  typeAliasesPackage: com.xy.assignment.entity
  configuration:
    map-underscore-to-camel-case: true
